proc import datafile="S:\Final_Project_Data\Diabetes_Data_Set.csv"out=Prevalence replace;
delimiter=',';
getnames=yes;
proc print;
run;

proc means mean std stderr clm p25 p50 p75;
title 'Breakdown of Prevalence';
var Diagnosed_Diabetes_Est__Percent;
run;
proc univariate data=Prevalence normal;
title 'Distribution of Prevalence';
/*creates histogram with normal density plotted on top of histogram*/
histogram / normal;
run;
*target; 
data Prevalence;
*source;
set Prevalence;
ln_UnemploymentRate=log(Unemployment_Rate);
*target; 
data Prevalence;
*source;
set Prevalence;
ln_MedianIncome=log(Household_Median_Income);
*target; 
data Prevalence;
*source;
set Prevalence;
ln_LessThanHighSchool=log(Percent_of_adults_with_less_than);
*target; 
data Prevalence;
*source;
set Prevalence;
ln_WithHighSchoolDiploma=log(Percent_of_adults_with_a_high_sc);
*target; 
data Prevalence;
*source;
set Prevalence;
ln_SomeCollege=log(Percent_of_adults_completing_som);
*target; 
data Prevalence;
*source;
set Prevalence;
ln_Bachelors=log(Percent_of_adults_with_a_bachelo);
*target; 
data Prevalence;
*source;
set Prevalence;
ln_Obesity=log(Obesity_Prev_Percent);
*target; 
data Prevalence;
*source;
set Prevalence;
ln_Inactivity=log(Leisure_Time_Physical_Inactivity);
*target; 
data Prevalence;
*source;
set Prevalence;
ln_Age=log(Median_Age);
proc print;
run;
proc univariate data=Prevalence normal;
histogram / normal;
run;
proc corr;
run;
proc sgscatter;
title'correlation of Diabete Indicators';
Matrix Diagnosed_Diabetes_Est__Percent ln_UnemploymentRate ln_MedianIncome ln_LessThanHighSchool ln_WithHighSchoolDiploma ln_SomeCollege ln_Bachelors ln_Obesity ln_Inactivity ln_Age;
run;
proc reg data=Prevalence;
title 'Transformed Independent Variables';
model Diagnosed_Diabetes_Est__Percent= ln_UnemploymentRate ln_MedianIncome ln_LessThanHighSchool ln_WithHighSchoolDiploma ln_SomeCollege ln_Bachelors ln_Obesity ln_Inactivity ln_Age/vif;
plot residual.*predicted.;
plot npp.*student.;
run;
proc reg;
title 'Regression Model to Determine Influential Points and Outliers';
model Diagnosed_Diabetes_Est__Percent =ln_UnemploymentRate ln_MedianIncome ln_LessThanHighSchool ln_WithHighSchoolDiploma ln_SomeCollege ln_Bachelors ln_Obesity ln_Inactivity ln_Age/influence r;
run;
data Prevalence;
set Prevalence;
if _n_ =60 then delete;
if _n_=2331 then delete;
if _n_=2419 then delete;
run;
proc reg data=Prevalence;
title 'Without Outliers in Data';
model Diagnosed_Diabetes_Est__Percent= ln_UnemploymentRate ln_MedianIncome ln_LessThanHighSchool ln_WithHighSchoolDiploma ln_SomeCollege ln_Bachelors ln_Obesity ln_Inactivity ln_Age;
run;
proc reg data=Prevalence;
title 'Strongest Predictors';
model Diagnosed_Diabetes_Est__Percent= ln_UnemploymentRate ln_MedianIncome ln_LessThanHighSchool ln_WithHighSchoolDiploma ln_SomeCollege ln_Bachelors ln_Obesity ln_Inactivity ln_Age/stb;
run;
title"Test and Train Sets for Diabetes Prevalence";
proc SURVEYSELECT data=Prevalence
out=xv_all SEED=71 SAMPRATE=0.75 OUTALL;
proc print;
run;

data xv_all;
set xv_all;
if selected then new_y=Diagnosed_Diabetes_Est__Percent;
run;
proc print data=xv_all;
run;
title"Model Selection";
proc reg data=xv_all;
*Model 1;
model new_y=ln_UnemploymentRate ln_MedianIncome ln_LessThanHighSchool ln_WithHighSchoolDiploma ln_SomeCollege ln_Bachelors ln_Obesity ln_Inactivity ln_Age/selection=stepwise;
*Model 2;
model new_y=ln_UnemploymentRate ln_MedianIncome ln_LessThanHighSchool ln_WithHighSchoolDiploma ln_SomeCollege ln_Bachelors ln_Obesity ln_Inactivity ln_Age/selection=cp;
run; 
title"Validation-Test Set";
proc reg data=xv_all;
*Model 1;
model new_y=ln_UnemploymentRate ln_MedianIncome ln_LessThanHighSchool ln_WithHighSchoolDiploma ln_SomeCollege ln_Obesity ln_Inactivity ln_Age;
output out=outm1(where=(new_y=.))p=yhat;
*Model 2;
model new_y=ln_UnemploymentRate ln_MedianIncome ln_LessThanHighSchool ln_WithHighSchoolDiploma ln_SomeCollege ln_Obesity ln_Inactivity ln_Age;
output out=outm2 (where=(new_y=.))p=yhat;
run;
proc print data=outm1;
run;
proc print data=outm2;
run;
proc corr;
run;
proc reg data=xv_all;
title 'Validation of Model';
model Diagnosed_Diabetes_Est__Percent=ln_UnemploymentRate ln_MedianIncome ln_LessThanHighSchool ln_WithHighSchoolDiploma ln_SomeCollege ln_Bachelors ln_Obesity ln_Inactivity ln_Age/vif;
plot residual.*predicted.;
plot npp.*student.;
run;
proc GLM;
class ln_MedianIncome ln_Inactivity
title "Interaction Terms";
model Diagnosed_Diabetes_Est__Percent=ln_MedianIncome ln_Inactivity ln_MedianIncome*ln_Inactivity;
run;
proc corr;
title"Interaction Variable Multicolinearity";
var Diagnosed_Diabetes_Est__Percent ln_MedianIncome ln_Inactivity;
run;
